import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Mogly",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-bg-primary px-6 py-16">
      <div className="mx-auto max-w-[640px]">
        <Link
          href="/"
          className="inline-flex items-center gap-1 text-xs text-text-muted hover:text-text-primary transition-colors mb-8"
        >
          ← Back to Mogly
        </Link>

        <h1 className="text-3xl font-bold text-text-primary mb-2">
          Terms of Service
        </h1>
        <p className="font-mono text-[11px] text-text-muted mb-10">
          Last updated: March 2026
        </p>

        <div className="flex flex-col gap-8 text-sm leading-relaxed">
          <Section title="Agreement">
            <p>
              By using Mogly, you agree to these terms. If you do not agree,
              please do not use the service.
            </p>
          </Section>

          <Section title="The Service">
            <p>
              Mogly is an AI-powered skin analysis tool that provides a
              numerical score and personalized insights based on selfie photos.
              The service is provided on an as-is basis.
            </p>
          </Section>

          <Section title="Age Requirement">
            <p>
              You must be at least 13 years old to use Mogly. By using the
              service, you confirm that you meet this age requirement.
            </p>
          </Section>

          <Section title="Subscriptions &amp; Billing">
            <ul className="list-disc list-inside space-y-2 text-text-muted">
              <li>
                Mogly Premium is available as a weekly ($9.99/week),
                monthly ($29.99/month), or annual ($99.99/year) subscription
              </li>
              <li>
                <strong className="text-text-primary">
                  Subscriptions auto-renew
                </strong>{" "}
                at the end of each billing period unless cancelled
              </li>
              <li>
                The weekly plan includes a 3-day free trial. You will be charged
                after the trial ends unless you cancel before then
              </li>
              <li>
                You can cancel your subscription at any time from your Account
                page or through Stripe&apos;s customer portal
              </li>
              <li>
                We offer a 7-day refund policy on your first purchase. Contact
                hello@getmogly.com for refund requests
              </li>
            </ul>
          </Section>

          <Section title="AI Disclaimer">
            <p>
              Mogly&apos;s skin analysis is generated by artificial intelligence
              and is for{" "}
              <strong className="text-text-primary">
                informational purposes only
              </strong>
              . It is not a medical diagnosis, prescription, or treatment plan.
              Always consult a licensed dermatologist or healthcare provider for
              skin concerns. Mogly is not responsible for decisions made based on
              its analysis.
            </p>
          </Section>

          <Section title="Your Content">
            <p>
              You retain ownership of all photos you upload. By uploading a
              photo, you grant Mogly a limited license to process it through our
              AI for the sole purpose of generating your skin analysis. We do
              not use your photos for any other purpose.
            </p>
          </Section>

          <Section title="Intellectual Property">
            <p>
              Mogly, including its design, code, algorithms, and branding, is
              owned by Mogly. You may not copy, reproduce, or create derivative
              works from the service without permission.
            </p>
          </Section>

          <Section title="Limitation of Liability">
            <p>
              Mogly is provided as-is without warranties of any kind. We are not
              liable for any damages arising from the use of our service,
              including but not limited to inaccurate analysis results, service
              interruptions, or data loss. Our total liability is limited to the
              amount you paid us in the 12 months preceding the claim.
            </p>
          </Section>

          <Section title="Termination">
            <p>
              We reserve the right to suspend or terminate your account if you
              violate these terms or misuse the service. You can delete your
              account at any time by contacting hello@getmogly.com.
            </p>
          </Section>

          <Section title="Changes to Terms">
            <p>
              We may update these terms from time to time. Continued use of
              Mogly after changes constitutes acceptance of the new terms.
            </p>
          </Section>

          <Section title="Contact">
            <p>
              Questions? Email us at{" "}
              <a
                href="mailto:hello@getmogly.com"
                className="text-accent-green hover:underline"
              >
                hello@getmogly.com
              </a>
            </p>
          </Section>
        </div>

        <div className="mt-16 text-center">
          <span className="font-mono text-[11px] text-[#333]">getmogly.com</span>
        </div>
      </div>
    </main>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section>
      <h2 className="text-lg font-bold text-text-primary mb-2">{title}</h2>
      <div className="text-text-muted">{children}</div>
    </section>
  );
}
